# Generated by Django 3.2.5 on 2021-07-13 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('speaker_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementTaskGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('max_value', models.FloatField(null=True)),
                ('min_value', models.FloatField(null=True)),
                ('text', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(default=None, max_length=255, null=True)),
                ('unit', models.CharField(default=None, max_length=255, null=True)),
                ('mode', models.CharField(choices=[('daily', 'DY'), ('weekly', 'WY'), ('monthly', 'MY')], max_length=7)),
                ('last_push', models.DateTimeField(default=None, null=True)),
                ('days_week_day', models.IntegerField(default=None, null=True)),
                ('days_week_hour', models.IntegerField(default=None, null=True)),
                ('hours', models.IntegerField(default=None, null=True)),
                ('days_month_day', models.IntegerField(default=None, null=True)),
                ('days_month_hour', models.IntegerField(default=None, null=True)),
                ('show', models.BooleanField(default=None, null=True)),
                ('max_value', models.FloatField(default=None, null=True)),
                ('min_value', models.FloatField(default=None, null=True)),
                ('for_pressure_field', models.TextField(default=None, null=True)),
                ('contract', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsenger_agent.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('contract', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsenger_agent.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('is_red', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsenger_agent.contract')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doctor_description', models.TextField()),
                ('patient_description', models.TextField()),
                ('thanks_text', models.TextField(null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsenger_agent.contract')),
                ('fields', models.ManyToManyField(to='medsenger_agent.MeasurementTaskGeneric')),
            ],
        ),
    ]
