# Generated by Django 3.2.5 on 2021-07-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medsenger_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtask',
            name='custom_text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='medicinetaskgeneric',
            name='prefix',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
