# Generated by Django 3.2.5 on 2021-07-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsenger_agent', '0002_auto_20210720_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinetaskgeneric',
            name='prefix',
        ),
        migrations.AddField(
            model_name='measurementtaskgeneric',
            name='prefix',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
