# Generated by Django 3.2.5 on 2021-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medsenger_agent', '0003_auto_20210720_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='medsenger_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='doctor', max_length=255),
        ),
    ]
