# Generated by Django 3.2.5 on 2021-07-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medsenger_agent', '0004_auto_20210721_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='version',
            field=models.CharField(default='null', max_length=13),
        ),
    ]
