# Generated by Django 3.2.5 on 2021-07-22 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('medsenger_agent', '0006_firmware'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firmware',
        ),
    ]
